### ISSUE TITLE
SOAPfilter_v2.2 does not use parallel cpus

### ISSUE THREAD

**Issue by ViriatoII** [BGI-Qingdao/stlfr2supernova_pipeline#2]
Hello,

I'm running the SOAPfilter for 12 hours and it's still halfway through to finish. The script is only using 1 cpu, even though I gave 12 in the -t parameter.

Here's the script being run:
`/...../stlfr2supernova/bin/SOAPfilter_v2.2 -q 33 -t 12 -y -F CTGTCTCTTATACACATCTTAGGAAGACAAGCACTGACGACATGA -R TCTGCTGAGTCGAGAACGTCTCTGTGAGCCAAGGAGTTGCTCTGG  -p -M 2 -f -1 -Q 10 lane.lst stat.txt >SOAPfilter__11_04_10_34_03.log 2>SOAPfilter__11_04_10_34_03.err || exit 1
`

(called by stlfr2supernova/step_1_filter.sh )

**Comment by cchd0001** [comment]
Hi Viriatoll

Since SOAPFilter was distrubuted in binary format, I was not able to get its souce codes to improve it. However, you could substitute it by any other quality-control tool to remove adaptors and PCR duplications as long as the tool doesn't modify the input read names. 

Best wishes
Lidong
